kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.nginx.port }}
    protocol: TCP
  {{- with .Values.service.labels }}
  selector:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  type: {{ .Values.service.type }}