
name: nginx-sampleapps

nginx:
  replicaCount: 2
  labels:
    app: nginx-sampleapps
  image:
    repository: nginx
    tag: ""
  port: 80

service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-layer-type: "nlb"
    service.beta.kubernetes.io/ncloud-load-balancer-size: "SMALL"
    service.beta.kubernetes.io/ncloud-load-balancer-internal: "false"